packages:
  - apps/*
  - packages/*

allowBuilds:
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  ssh2: false

catalog:
  '@opentelemetry/api': 1.9.1
  '@sinclair/typebox': 0.34.52
  ajv: 8.20.0
  ajv-formats: 3.0.1
  bullmq: 5.80.10
  drizzle-orm: 0.45.2
  fastify: 5.10.0
  ioredis: 5.11.1
  pg: 8.22.0
  pino: 10.3.1
  react: 19.2.8
  react-dom: 19.2.8
  tsup: 8.5.1
  uuid: 14.0.1

minimumReleaseAgeExclude:
  - '@next/env@16.2.11'
  - '@next/swc-darwin-arm64@16.2.11'
  - '@next/swc-darwin-x64@16.2.11'
  - '@next/swc-linux-arm64-gnu@16.2.11'
  - '@next/swc-linux-arm64-musl@16.2.11'
  - '@next/swc-linux-x64-gnu@16.2.11'
  - '@next/swc-linux-x64-musl@16.2.11'
  - '@next/swc-win32-arm64-msvc@16.2.11'
  - '@next/swc-win32-x64-msvc@16.2.11'
  - bullmq@5.80.10
  - next@16.2.11
  - prettier@3.9.6
  - react-dom@19.2.8
  - react@19.2.8
  - '@opentelemetry/api-logs@0.221.0'
  - '@opentelemetry/configuration@0.221.0'
  - '@opentelemetry/context-async-hooks@2.10.0'
  - '@opentelemetry/core@2.10.0'
  - '@opentelemetry/exporter-logs-otlp-grpc@0.221.0'
  - '@opentelemetry/exporter-logs-otlp-http@0.221.0'
  - '@opentelemetry/exporter-logs-otlp-proto@0.221.0'
  - '@opentelemetry/exporter-metrics-otlp-grpc@0.221.0'
  - '@opentelemetry/exporter-metrics-otlp-http@0.221.0'
  - '@opentelemetry/exporter-metrics-otlp-proto@0.221.0'
  - '@opentelemetry/exporter-prometheus@0.221.0'
  - '@opentelemetry/exporter-trace-otlp-grpc@0.221.0'
  - '@opentelemetry/exporter-trace-otlp-http@0.221.0'
  - '@opentelemetry/exporter-trace-otlp-proto@0.221.0'
  - '@opentelemetry/exporter-zipkin@2.10.0'
  - '@opentelemetry/instrumentation@0.221.0'
  - '@opentelemetry/otlp-exporter-base@0.221.0'
  - '@opentelemetry/otlp-grpc-exporter-base@0.221.0'
  - '@opentelemetry/otlp-transformer@0.221.0'
  - '@opentelemetry/propagator-b3@2.10.0'
  - '@opentelemetry/propagator-jaeger@2.10.0'
  - '@opentelemetry/resources@2.10.0'
  - '@opentelemetry/sdk-logs@0.221.0'
  - '@opentelemetry/sdk-metrics@2.10.0'
  - '@opentelemetry/sdk-node@0.221.0'
  - '@opentelemetry/sdk-trace-base@2.10.0'
  - '@opentelemetry/sdk-trace-node@2.10.0'
  - '@opentelemetry/sdk-trace@2.10.0'

overrides:
  sharp: 0.35.3
