import { Type, type Static } from '@sinclair/typebox';

export const ErrorDetailsSchema = Type.Optional(
  Type.Record(Type.String({ maxLength: 100 }), Type.Unknown(), {
    maxProperties: 25,
  }),
);

export const ErrorEnvelopeSchema = Type.Object(
  {
    error: Type.Object(
      {
        code: Type.String({ maxLength: 80, minLength: 1, pattern: '^[A-Z][A-Z0-9_]*$' }),
        details: ErrorDetailsSchema,
        message: Type.String({ maxLength: 300, minLength: 1 }),
        requestId: Type.String({ format: 'uuid' }),
      },
      { additionalProperties: false },
    ),
  },
  { $id: 'ErrorEnvelopeV1', additionalProperties: false },
);

export type ErrorEnvelope = Static<typeof ErrorEnvelopeSchema>;

export const ErrorCodes = {
  advanceLimitExceeded: 'ADVANCE_LIMIT_EXCEEDED',
  accountingUnbalanced: 'ACCOUNTING_UNBALANCED',
  authenticationFailed: 'AUTHENTICATION_FAILED',
  clockNotPaused: 'CLOCK_NOT_PAUSED',
  clockNotRunning: 'CLOCK_NOT_RUNNING',
  csrfInvalid: 'CSRF_INVALID',
  dependencyNotReady: 'DEPENDENCY_NOT_READY',
  economyAlreadyInitialized: 'ECONOMY_ALREADY_INITIALIZED',
  economyIntegerOverflow: 'ECONOMY_INTEGER_OVERFLOW',
  economyNotInitialized: 'ECONOMY_NOT_INITIALIZED',
  forbidden: 'FORBIDDEN',
  idempotencyConflict: 'IDEMPOTENCY_CONFLICT',
  idempotencyKeyReused: 'IDEMPOTENCY_KEY_REUSED',
  internal: 'INTERNAL_ERROR',
  invitationNotAvailable: 'INVITATION_NOT_AVAILABLE',
  invalidAmountFormat: 'INVALID_AMOUNT_FORMAT',
  invalidCursor: 'INVALID_CURSOR',
  invalidContentType: 'INVALID_CONTENT_TYPE',
  invalidRequest: 'INVALID_REQUEST',
  expectedTickMismatch: 'EXPECTED_TICK_MISMATCH',
  notFound: 'NOT_FOUND',
  noCompatiblePrimitives: 'NO_COMPATIBLE_PRIMITIVES',
  insufficientFunds: 'INSUFFICIENT_FUNDS',
  insufficientInventory: 'INSUFFICIENT_INVENTORY',
  operationalSmokeDisabled: 'OPERATIONAL_SMOKE_DISABLED',
  payloadTooLarge: 'PAYLOAD_TOO_LARGE',
  currencyFrozen: 'CURRENCY_FROZEN',
  primitiveFamilyConflict: 'PRIMITIVE_FAMILY_CONFLICT',
  primitiveImmutable: 'PRIMITIVE_IMMUTABLE',
  primitiveNotPublished: 'PRIMITIVE_NOT_PUBLISHED',
  primitiveVersionExists: 'PRIMITIVE_VERSION_EXISTS',
  queryTooLarge: 'QUERY_TOO_LARGE',
  rateLimited: 'RATE_LIMITED',
  registrationUnavailable: 'REGISTRATION_UNAVAILABLE',
  reauthenticationFailed: 'REAUTHENTICATION_FAILED',
  recentCredentialInvalid: 'RECENT_CREDENTIAL_INVALID',
  recentCredentialRequired: 'RECENT_CREDENTIAL_REQUIRED',
  retrievalUnavailable: 'RETRIEVAL_UNAVAILABLE',
  scheduleAlreadyTerminal: 'SCHEDULE_ALREADY_TERMINAL',
  scheduleInPast: 'SCHEDULE_IN_PAST',
  seedPlanIncompatible: 'SEED_PLAN_INCOMPATIBLE',
  seedPlanHashMismatch: 'SEED_PLAN_HASH_MISMATCH',
  simulationBudgetExceeded: 'SIMULATION_BUDGET_EXCEEDED',
  simulationHandlerFailed: 'SIMULATION_HANDLER_FAILED',
  simulationIntegerOverflow: 'SIMULATION_INTEGER_OVERFLOW',
  simulationProcessUnknown: 'SIMULATION_PROCESS_UNKNOWN',
  simulationProcessVersionMismatch: 'SIMULATION_PROCESS_VERSION_MISMATCH',
  staleVersion: 'STALE_VERSION',
  supplyCapExceeded: 'SUPPLY_CAP_EXCEEDED',
  unauthorized: 'UNAUTHORIZED',
  validationFailed: 'VALIDATION_FAILED',
  worldNotActive: 'WORLD_NOT_ACTIVE',
  currencyMismatch: 'CURRENCY_MISMATCH',
  walletFrozen: 'WALLET_FROZEN',
  walletNotControlled: 'WALLET_NOT_CONTROLLED',
  assetNotOwned: 'ASSET_NOT_OWNED',
  assetNotTransferable: 'ASSET_NOT_TRANSFERABLE',
  offerExpired: 'OFFER_EXPIRED',
  offerNotOpen: 'OFFER_NOT_OPEN',
  offerNotDue: 'OFFER_NOT_DUE',
  quantityInvalid: 'QUANTITY_INVALID',
  recipeInvalid: 'RECIPE_INVALID',
  productionStateInvalid: 'PRODUCTION_STATE_INVALID',
  contractStateInvalid: 'CONTRACT_STATE_INVALID',
  jobCooldown: 'JOB_COOLDOWN',
  jobCapExceeded: 'JOB_CAP_EXCEEDED',
  listingStale: 'LISTING_STALE',
  listingExpired: 'LISTING_EXPIRED',
  listingNotOpen: 'LISTING_NOT_OPEN',
  policyInvalid: 'POLICY_INVALID',
  conflict: 'CONFLICT',
  buyerMismatch: 'BUYER_MISMATCH',
  ownershipConflict: 'OWNERSHIP_CONFLICT',
  worldSlugTaken: 'WORLD_SLUG_TAKEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
